import fs from "fs";
import path from "path";
import Head from "next/head";
import React from "react";

export default function Home({ posts }) {
  console.log(posts);
  return (
    <React.Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>GDSC KWASU's Blog</h1>
    </React.Fragment>
  );
}

export async function getStaticProps() {
  // obtain blog posts from the "/posts" directory
  const files = fs.readdirSync(path.join("posts"));

  // getting the frontmatter/blog post excerpt from
  // the posts directory in each file
  const posts = files.map((filename) => {
    const slug = filename.replace(".md", "");

    return {
      slug,
    };
  });

  console.log(posts);
  return {
    props: {
      posts: "GDSC Kwasu blog posts",
    },
  };
}
